---

# Install kubeadmin

#- name: Install kubeadm # ansible bug 29705
#  package: 
#    name: "{{ item }}-{{ kubeadm_version | regex_replace('v') }}*" 
#    state: present
#  environment: "{{ proxy_env | default ({}) }}"
#    http_proxy: '{{ proxy_env.http_proxy }}'
#    https_proxy: '{{ proxy_env.https_proxy }}'
#  with_items:
#  - kubeadm
#  when: kubeadm_version is defined and ansible_os_family == "Debian"


- name: Install kubeadm # ansible bug 29705
  apt:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env | default ({}) }}"
#    http_proxy: '{{ proxy_env.http_proxy }}'
#    https_proxy: '{{ proxy_env.https_proxy }}'
  with_items:
  - kubeadm
  when: kubeadm_version is defined and ansible_os_family == "Debian"
