---
# Install kebelet

- name: Install kubelet
  apt:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env | default ({}) }}"
  with_items:
#  - kubelet="{{ kubelet_version | replace('v', '') }}*"
   - kubelet
  when: kubelet_version is defined and ansible_os_family == "Debian"

