---

# Install kubeadmin

- name: Install kubeadm # ansible bug 29705
  apt:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env | default ({}) }}"
  with_items:
  - kubeadm
  when: kubeadm_version is defined and ansible_os_family == "Debian"
