- name: 'Deploy k8s {{ Role }} HA'
  hosts: master-primary
  roles:
    - { role: common }
    - { role: kubeadmin }
    - { role: k8s-master-primary, tags: ['deploy'] }
  vars:
    servicesubnet: 10.10.0.0/24
    podsunbet: 10.20.0.0/24
    dnsDomain: cluster.local
    proxy_env:
      http_proxy: http://172.16.1.112:10809
      https_proxy: http://172.16.1.112:10809
    localtions: Asia/Shanghai  
    KUBERNETES_VERSION: 1.18.2
 #To do:
    #cloudProvider:

