---
  - set_fact:
      env_kc: '{{ proxy_env |default({}) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
    when: proxy_env is defined
#    tags:
#    - always

  # PULL IMAGES
  # docker_images module support from ansible2.8
  #  - name: Pull k8s images from {{ gcr_url  }}
  #  docker_image:
  #    name: "{{ item.name }}"
  #    tags: "{{ item.tag }}"
  #    source:
  #      pull: yes
  #  with_items: "{{ K8S_IMAGES }}" 
  #  when: localtions != 'Asia/Shanghai'

  #  - name: Pull k8s images from {{ ali_url  }}
  #  docker_image:
  #    name: "{{ item.name }}"
  #    tags: "{{ item.tag }}"
  #    #source: pull
  #    #source:
  #    pull: yes
  #  with_items: "{{ K8S_IMAGES | replace(gcr_url, ali_url) }}"
  #  when: localtions == 'Asia/Shanghai'

  - name: Pull k8s images from {{ gcr_url  }}
    raw: docker pull {{ item.name }}:{{ item.tag }}
    with_items: "{{ K8S_IMAGES }}"
    when: localtions != 'Asia/Shanghai'
    tags:
      - deploy

  - name: Pull k8s images from {{ ali_url  }}
    raw: docker pull {{ item.name }}:{{ item.tag }}
    with_items: "{{ K8S_IMAGES | replace(gcr_url, ali_url) }}"
    when: localtions == 'Asia/Shanghai'    
    tags:
      - deploy
