---
## initial master role

  - name: Make sure /etc/kubernetes folder exists
    file: path=/etc/kubernetes/ state=directory mode=0755

  - name: Install kubeadm config file
    template: src=configfile.yaml.j2 dest=/etc/kubernetes/configfile.yaml owner=root group=root mode=400
    tags:
      - deploy
  
  - name: Initialize cluster on primary master with kubeadm init {{ kubeadm_init_args }} --config /etc/kubernetes/kubeadm-master.conf --upload-certs
#    command: /usr/bin/kubeadm init "{{ kubeadm_init_args | default() }}" --config /etc/kubernetes/configfile.yaml --upload-certs
    command: /usr/bin/kubeadm init --config /etc/kubernetes/configfile.yaml --upload-certs --v=5
    register: kubeadm_init_primary
    tags:
     - deploy

  - name: Kubeadm_init_primary output
    debug: 
      msg: "{{ kubeadm_init_primary.stdout_lines }}"

  - name: Generate token
    raw: kubeadm token create --print-join-command
    register: token
    tags:
      - join

#  - name: Display token
#    debug: 
#      msg: "{{ token.stdout | regex_replace('.*WARNING.*\r\n', '') }}"
#    register: message
#    tags:
#      - join
