---
enable_proxy: true
#proxy_env:
#  http_proxy: http://172.16.1.112:10809
#  https_proxy: http://172.16.1.112:10809

KUBERNETES_VERSION: "1.18.4"

gcr_url: gcr.io/google-containers
ali_url: registry.cn-hangzhou.aliyuncs.com/google_containers

kube_path: /etc/kubernetes

K8S_IMAGES:
  - - { name: "{{ gcr_url }}/kube-scheduler-amd64", tag: "v{{ KUBERNETES_VERSION }}" }
    - { name: "{{ gcr_url }}/kube-controller-manager-amd64", tag: "v{{ KUBERNETES_VERSION }}" }
    - { name: "{{ gcr_url }}/kube-apiserver-amd64", tag: "v{{ KUBERNETES_VERSION }}" }

network_addon: flannel

flannel_url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
Calico_url: "https://docs.projectcalico.org/v3.14/manifests/calico.yaml"
Cilium_url: "https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml"
