---
  - name: Set hostname
    hostname: name={% if host_Name is defined %}{{ host_Name }}{% else %}{{ Role }}-{{ address | replace('.', '-') }}{% endif %}

  - name: Install sysctl settings
    template: src=sysctl.conf.j2 dest=/etc/sysctl.conf owner=root group=root mode=400
  
  #resolve:
  #error: "net.bridge.bridge-nf-call-iptables" is an unknown key
  #error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
  #error: "net.bridge.bridge-nf-call-arptables" is an unknown key
  - name: Install bridge module
    modprobe:
      name: bridge
      state: present

  #resolve:
  #sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-ip6tables: No such file or directory
  #sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory
  - name: Install br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Apply sysctl settings
    command: sysctl -p /etc/sysctl.conf
